Feature/12 sign up page frontend
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #14
Opened 2020-08-05 10:35 UTC by EugeneMusievskyi

2020-08-05 17:38 UTC, klesogor requested changes
В целом ок, но работу с dom-ом точно нужно выпилить. Также сегодня постараемся смерджить ветку с формиком, форму нужно будет переписать с его использованием. Для валидации советую подключить yup

2020-08-05 17:38 UTC, klesogor commented on frontend/src/components/RegistrationForm/index.tsx
> +        const validationMessage = document.getElementById("company-validation");
стоит избегать работы с DOM напрямую в реакте, особенно в функции валидации, т.к. её тип превращается из boolean в IO[Boolean](boolean + сайд эффект)

2020-08-06 21:15 UTC, EugeneMusievskyi commented
Я переписал код. Вроде всё работает правильно.

2020-08-07 06:20 UTC, klesogor requested changes
Разреши конфликты

2020-08-07 06:20 UTC, klesogor commented on frontend/src/components/RegistrationForm/index.tsx
> +            validationSchema={Yup.object({
validation schema будет создаваться на каждый ре-рендер

2020-08-07 19:30 UTC, klesogor approved these changes

2020-08-07 19:30 UTC, merged