Feature/42 user details
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #16
Opened 2020-08-05 12:37 UTC by grytsiuko

Созданы две сущности и миграции - UserProfile & UserSettings. Телефон я оставил не уникальным, так как если делать его потенциальным ключем, то тогда уже стоит переместить в базовую сущность, если он идентифицирует юзера.

2020-08-05 17:32 UTC, klesogor requested changes

2020-08-05 17:32 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/UserService.java
> +            var user = new User(userDto.getId(), userDto.getEmail(), userDto.getUsername(), userDto.getPassword(), new ArrayList<>(), new ArrayList<>(), null, null);
Стоит переписать на билдер, аннотация на моделе уже есть. Также при создании юзера для него должны создаваться записи UserProfile и UserSettings по-умолчанию

2020-08-05 17:32 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
> +    @OneToOne(mappedBy = "user")
Возможно, тут стоит явно указать Cascade тип

2020-08-06 06:16 UTC, grytsiuko commented on backend/core/src/main/java/com/feed_grabber/core/user/UserService.java
> +            var user = new User(userDto.getId(), userDto.getEmail(), userDto.getUsername(), userDto.getPassword(), new ArrayList<>(), new ArrayList<>(), null, null);
Сейчас перепишу. Смотрю в UserCreateDto есть поле id, может удалить его? При создании ж id не указывается

2020-08-06 06:22 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/UserService.java
> +            var user = new User(userDto.getId(), userDto.getEmail(), userDto.getUsername(), userDto.getPassword(), new ArrayList<>(), new ArrayList<>(), null, null);
Не стоит, тот кто будет прикручивать регистрацию перепишет DTO

2020-08-06 06:57 UTC, grytsiuko commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
>      private List<Role> roles = new ArrayList<>();
Тут стоит связь @OneToMany
Если у нас стоит связь Юзер-Роль как много-один, надо ж тогда @ManyToOne и Role вместо List<Role>
Плюс, в миграции нету поля role_id.
Мне это исправить в моей ветке?

2020-08-06 06:57 UTC, grytsiuko commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
>      private List<Role> roles = new ArrayList<>();
В схеме БД кстати тоже на одного Юзера много Ролей в связи, хотя FK правильно стоит

2020-08-06 08:09 UTC, klesogor approved these changes

2020-08-06 08:09 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
>      private List<Role> roles = new ArrayList<>();
Это уже поправили в ветке с ролями, теперь из-за этого конфликт

2020-08-06 08:10 UTC, klesogor commented
Когда будешь резолвить конфликт, глянь пожалуйста повесил ли я со стороны модели User что Not Null аннотацию на роль

2020-08-06 08:51 UTC, merged