#13 Roles update
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #18
Opened 2020-08-05 15:23 UTC by MaksymSlobodianyk

2020-08-05 17:17 UTC, klesogor requested changes
Критических замечаний нет, но по мелочи нужно поправить. Также было бы неплохо вернуть схему БД перед мерджем

2020-08-05 17:17 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/role/Role.java
> +    private String systemRole;
это поле точно должно быть типа SystemRole

2020-08-05 17:17 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/role/Role.java
> +    private String systemRole;
https://www.baeldung.com/jpa-persisting-enums-in-jpa

2020-08-05 17:17 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
> +    @JoinColumn(name = "id")
По текущей лоигке у юзера должна быть одна роль

2020-08-05 17:17 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/role/dto/RoleDetailsDto.java
> +    String systemRole;
Jakson должен справится с сериализацией энама, лучше поменять на SystemRole

2020-08-05 17:17 UTC, klesogor commented on backend/core/src/main/resources/db/migration/V2020.08.05_14.25__create_role_table.sql
> +    system_role varchar(16),
лучше взять с запасом, 32 или 64 символа

2020-08-05 18:29 UTC, MaksymSlobodianyk commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
> +    @JoinColumn(name = "id")
Слушне зауваження, зараз виправлю. А чи повинен я додати колонку id ролі до юзера в міграції , оскільки зараз її в ньому немає. Чи це повинна буде зробити людина, яка писала модель юзера?

2020-08-06 07:45 UTC, klesogor approved these changes

2020-08-06 07:45 UTC, klesogor commented on backend/core/src/main/resources/db/migration/V2020.08.05_23.12__create_user_table.sql
> +    role_id uuid,
нельзя изменять уже существующие миграции, если надо что-то поменять, создавай новые

2020-08-06 07:46 UTC, merged