Task 49. Complete with details
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #31
Opened 2020-08-07 09:25 UTC by lenazelenaya

2020-08-07 12:01 UTC, muroslavko approved these changes

2020-08-07 19:48 UTC, klesogor requested changes
ПР готов к мерджу. Перенеси компонент в другую папку и опционально типизируй type

2020-08-07 19:48 UTC, klesogor commented on frontend/src/components/QuestionDetails/index.tsx
> +  const [question, setQuestion] = useState(undefined);
компилятор не сможет вывести тип [question], стоит типизировать useState<T>()

2020-08-07 19:48 UTC, klesogor commented on frontend/src/components/QuestionDetails/index.tsx
> +  useEffect(() => {
это вроде компонент, а не контейнер, сайд эффектов тут быть не должно

2020-08-07 19:48 UTC, klesogor commented on frontend/src/components/QuestionDetails/index.tsx
> +  const [question, setQuestion] = useState(undefined);
Если он будет идти в формате модалки его лучше вынести в контейнеры

2020-08-07 19:48 UTC, klesogor commented on frontend/src/components/QuestionDetails/index.tsx
> +    switch (type) {
типизировать тип было бы неплохо. Сделать это можно или через enum или через
```
const questionTypes = ["input-field", "checkbox", ...] as const;
const QuestionType = questionTypes[number]// "input-field" | "checkbox" | ...
```

2020-08-08 14:29 UTC, klesogor approved these changes

2020-08-08 14:29 UTC, merged