Connect company feed
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #345
Opened 2020-09-05 20:24 UTC by TheBestTvarynka

2020-09-05 20:30 UTC, TheBestTvarynka commented on backend/core/src/main/java/com/feed_grabber/core/news/NewsService.java
The image is an optional thing. So it ca does not exist in the news.

2020-09-06 07:14 UTC, MaksymSlobodianyk requested changes

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/components/CompanyFeedItemCreation/index.tsx
> +      console.log(imageId);
Delete console.log please

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/components/CompanyFeedItemCreation/index.tsx
> +      console.log(res.data);
Delete console.log please

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/components/CompanyFeedItemCreation/index.tsx
> +      console.log({ newItem });
Delete console.log please

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/components/CompanyFeedItemCreation/index.tsx
> +      console.log(item);
Delete console.log please

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/components/MainPage/index.tsx
> +//     newsList?: INewsItem[];
Delete redudant commented code please

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/models/companyFeed/ICompanyFeedItem.ts
> +//   isLoading: boolean;
Delete redudant commented code please

2020-09-06 07:14 UTC, MaksymSlobodianyk commented on frontend/src/containers/Routing/index.tsx
>  // just for demo
Do we have something here that we need just for demo, or it is just an old comment?

2020-09-06 12:09 UTC, TheBestTvarynka commented on frontend/src/components/NewsList/index.tsx
> +      </AccessManager>
Only hr and company owner can create a new items for company feed.

2020-09-06 14:21 UTC, MaksymSlobodianyk approved these changes

2020-09-06 14:59 UTC, merged