#55 feature link teams functionality
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #36
Opened 2020-08-07 18:20 UTC by AlexandrKarpachov

2020-08-07 20:07 UTC, klesogor requested changes
Посмотри сагу, точно ли yield не забыл и подумай насчет переписать на функциональный компонент, но это не обязательно

2020-08-07 20:07 UTC, klesogor commented on frontend/src/containers/TeamsPage/sagas.tsx
> +      loadTeamsRoutine.failure(error);
ты ничего не yield-ишь, так и должно быть?

2020-08-07 20:07 UTC, klesogor commented on frontend/src/containers/TeamsPage/index.tsx
> +  static getDerivedStateFromProps(nextProps, prevState) {
У компонента нет стейта, может стоит заменить на классовый компонент?
Также  этот метод можно переписать через тернарник или отказаться от esle, например
```
static getDerivedStateFromProps(nextProps, prevState){
  return nextProps.teams.length !== prevState.teams.length 
    ?  {teams: nextProps.teams}
    :  null;
}
```
или
```
static getDerivedStateFromProps(nextProps, prevState){
 if(nextProps.teams.length === prevState.teams.length){
    return null;
  } 

  return {teams: nextProps.teams};
}
```

2020-08-08 07:54 UTC, AlexandrKarpachov commented
> Посмотри сагу, точно ли yield не забыл и подумай насчет переписать на функциональный компонент, но это не обязательно

сагу исправил, переделал на фк

2020-08-10 06:24 UTC, muroslavko approved these changes

2020-08-10 06:42 UTC, klesogor approved these changes

2020-08-10 08:43 UTC, merged