#33 Authentication backend
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #7
Opened 2020-08-04 15:28 UTC by MaksymSlobodianyk

2020-08-04 18:57 UTC, klesogor requested changes
Хорошая работа. Поправь замечания и можно мерджить :+1:

2020-08-04 18:57 UTC, klesogor commented on backend/core/build.gradle
> +	implementation "io.jsonwebtoken:jjwt-api:0.10.5"
вынеси эти зависимости перед testImplementation

2020-08-04 18:57 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/auth/dto/TokenRefreshResponseDTO.java
> +@Data
DTO иммутабельны, поэтому для них лучше использовать аннотацию @Value

2020-08-04 18:57 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/security/JwtRequestFilter.java
> +        if (token != null) {
стоит переписать на early return, чтобы уменьшить цикломатическую сложность:
```
if(token == null){
  return null;
}
//get user stuff
if(user != null && !tokenService...){
 return new usernamePasswordAuthentication(...);
}

return null
```

2020-08-04 18:57 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/auth/dto/TokenRefreshRequestDTO.java
> +@Data
https://projectlombok.org/features/Value

2020-08-05 05:43 UTC, MaksymSlobodianyk commented on backend/core/src/main/java/com/feed_grabber/core/auth/dto/TokenRefreshRequestDTO.java
> +@Data
TokenRefreshRequestDTO є параметром @RequestBody в одному з методів контроллера та для десеріалізації повинно мати конструктор без параметрів, але це неможливо з @Value, тоді залишати @Data?

2020-08-05 06:13 UTC, klesogor requested changes
Поправь кусок с излишней вложенностью через early return и будем мерджить

2020-08-05 06:13 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/auth/dto/TokenRefreshRequestDTO.java
> +@Data
Да, на входящие DTO можно навешивать Data, извини, не заметил

2020-08-05 06:13 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/auth/dto/TokenRefreshResponseDTO.java
> +@Data
Здесь лучше всё же `@Value`, но ладно, это не принципиально

2020-08-05 06:13 UTC, klesogor commented on backend/core/src/main/resources/application.properties
> +auth0.secret-key:eyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJKb2UifQ1KP0SsvENi7Uz1oQc07aXTL7kpQG5jBNIybqr601234561dds
Почему `:` , а не `=` ?

2020-08-05 07:33 UTC, klesogor approved these changes

2020-08-05 07:33 UTC, merged