#90 questionnaire response with mock
BinaryStudioAcademy/bsa-2020-feedgrabber pull request #85
Opened 2020-08-13 06:52 UTC by NataNorth

2020-08-13 12:10 UTC, muroslavko submitted a review, later dismissed

2020-08-14 06:24 UTC, klesogor requested changes
Похоже, дев криво слился с твоей веткой и ты затерла много изменений других ребят. Внимательно пересмотри пулл реквест и исправь его пожалуйста.

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/auth/security/SecurityConstants.java
> -            "/api/user/email/reset",
Эти роуты должны быть доступны публично

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/question/QuestionType.java
> -    FREE_TEXT("free_text"),
Эти изменения также нужны

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/questionCategory/model/QuestionCategory.java
> -@Table(name = "question_categories", uniqueConstraints = {@UniqueConstraint(columnNames = {"title", "company_id"})})
констрейнты правильные, они нужны

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/UserController.java
> -    @ApiOperation(value = "Send an email to reset password")
Сброс пароля зачем удалять?

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/UserRepository.java
> -
скорее всего где-то эти методы используются

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/UserService.java
> -    public List<UserDetailsResponseDTO> getAllByCompanyId(UUID companyId, Integer page, Integer size) {
нужно для логина

2020-08-14 06:24 UTC, klesogor commented on backend/core/src/main/java/com/feed_grabber/core/user/model/User.java
> -        @UniqueConstraint(columnNames = {"email", "company_id"}),
констрейнты

2020-08-14 09:14 UTC, klesogor approved these changes

2020-08-14 09:14 UTC, klesogor commented on frontend/src/sagas/responseAnswers/sagas.ts
> +           `http://localhost:5000/api/answers/list`, action.payload);
захардкоженные урлы сломаются после деплоя

2020-08-14 09:14 UTC, merged